# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # --- CRITICAL: SCRAPING THE PUSHGATEWAY SERVICE ---
  - job_name: 'water_simulator'
    static_configs:
      - targets: ['pushgateway:9091'] # Use the service name
    honor_labels: true

     # Check that this target is present and correct:
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']